### ISSUE TITLE
[Not really an issue] Is there a watered down version of this?

### ISSUE THREAD

**Issue by monstermac77** [alexander-clarke/openvr-room-mapping#1]
I was directed to your post on Reddit about this. It looks incredibly cool, but it's pretty far overkill for what I'm looking for. I just want to, even if it's manually, match the layout of furniture in Steam VR home to exactly match that of my room so that I can jump on my virtual sofa and not plummet to the ground. 

The two main issues I'm having is it's easy to accidentally move virtual furniture once you've perfectly aligned and sized it, and it's easy to accidentally reset your standing position so your virtual room still matches your real room, but just rotated x degrees. Figured you'd have a lot of experience with this sort of thing!

**Comment by alexander-clarke** [comment]
Yeah, this doesn't solve all the problems yet
You could do this solution, then use it as reference to place downloaded 3D models of different parts of your apartment, and then use that as a custom steamvr environment, or just use the model generated from this solution directly as a custom steamvr environment.

This solves the easily moving virtual furniture problem, but doesn't solve the resetting standing position problem. I was looking into trying to fix the standing position problem, and it should be possible but I haven't looked into it, and would probably be a lot easier if there was some solution from Valve regarding that.

**Comment by monstermac77** [comment]
Got it, thanks so much! My temporary method of dealing with it is by standing in one corner of the room, drawing my bounds in the headset's native app (e.g. Oculus for Rift S, WMR home for Reverb, etc.) while standing in that corner. Then I open up Steam VR home and stay where I'm standing, and tap the reset standing position button and "reset" button on the environment (I'm not sure what if anything these things do; this is just precautionary to some extent because I don't want to spend the time understanding why things might go wrong if I don't do this). Then _without jumping around using the controller_ (this part I do know is critical), I walk around my room and once I come to a bound I place my bed at that bound and size it correctly (same with my TV, gaming PC, etc). Throughout this process I am constantly saving my environment in the Steam VR settings. 

This works! Anytime I leave and come back to Steam VR home, my virtual bed lines up perfectly with my real bed so I can walk over to my virtual bed and lie down. If I accidentally or intentionally teleport using the controller in Steam VR home (thus decoupling the mapping between my virtual room and real room) I can just go to the environments page and tap "Go Home" and that resets it all as intended and wherever I am in the real world I am standing there in VR space too. The convenience of the doing this all from a corner, I believe, is that if your bounds get deleted or you want to redraw them, you can go back and stand in that corner and redraw them and all still works well. It's basically just there as an anchor point. 

Of course, if you want to face a different direction when playing a game, you can still use the "reset standing position" in Steam when in the game and your real to virtual room coupling is not permanently disturbed.
